site_name: Qualidades de Software 1 - Villela & Andrade
repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-1-T01-Mateus-Villela-Raissa-Andrade
site_author: Mateus Villela & Raissa Andrade
repo_name: 2025-1-T01-Mateus-Villela-Raissa-Andrade

theme:
  name: material
  features:
    - navigation.tabs
  logo: 'assets/imgs/logo.svg'
  favicon: 'assets/imgs/agromart.ico'

  palette:
    - scheme: default
      primary: "#387F4A" 
      accent: "#F6C94A"
      toggle:
        icon: material/brightness-7   
        name: Switch to dark mode

    - scheme: slate
      primary: "#A7D0AC" 
      accent: "#FFD873"
      toggle:
        icon: material/brightness-4   
        name: Switch to light mode

  extra:
  toc:
    integrate: true

nav:
  - Visão Geral: index.md
  - Gerência:
      - Panorama do Processo: gerencia/panorama-de-processo.md
      - Etapa 1 - Comprometimento com a Medição: gerencia/estabelecimento.md
      - Etapa 2 - Planejamento da Medição: gerencia/planejamento.md
      - Etapa 3 - Implementação da Medição: gerencia/implementacao/preambulo.md
      - Etapa 4 - Avaliação da Medição: gerencia/avaliacao.md
  - Fases do Projeto:
      - Fase 1: Fase1.md
      - Fase 2: Fase2.md
      - Fase 3: Fase3.md
      - Fase 4: Fase4.md

markdown_extensions:
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search